
/*
 * Copyright (c) 2016 Dell Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License. You may obtain
 * a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * THIS CODE IS PROVIDED ON AN  *AS IS* BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT
 *  LIMITATION ANY IMPLIED WARRANTIES OR CONDITIONS OF TITLE, FITNESS
 * FOR A PARTICULAR PURPOSE, MERCHANTABLITY OR NON-INFRINGEMENT.
 *
 * See the Apache Version 2.0 License for specific language governing
 * permissions and limitations under the License.
 */


/*!
 * \file   nas_qos_wred.cpp
 * \brief  NAS QOS WRED Object
 */

#include "event_log.h"
#include "std_assert.h"
#include "nas_qos_common.h"
#include "nas_qos_wred.h"
#include "dell-base-qos.h"
#include "nas_ndi_qos.h"
#include "nas_base_obj.h"
#include "nas_qos_switch.h"

nas_qos_wred::nas_qos_wred (nas_qos_switch* switch_p)
           : base_obj_t (switch_p)
{
    memset(&cfg, 0, sizeof(cfg));
    wred_id = 0;
}

const nas_qos_switch& nas_qos_wred::get_switch()
{
    return static_cast<const nas_qos_switch&> (base_obj_t::get_switch());
}


void nas_qos_wred::commit_create (bool rolling_back)

{
    base_obj_t::commit_create(rolling_back);
}

void* nas_qos_wred::alloc_fill_ndi_obj (nas::mem_alloc_helper_t& m)
{
    // NAS Qos wred does not allocate memory to save the incoming tentative attributes
    return this;
}

bool nas_qos_wred::push_create_obj_to_npu (npu_id_t npu_id,
                                     void* ndi_obj)
{
    ndi_obj_id_t ndi_wred_id;
    t_std_error rc;

    EV_LOG_TRACE(ev_log_t_QOS, 3, "NAS-QOS", "Creating obj on NPU %d", npu_id);

    nas_qos_wred * nas_qos_wred_p = static_cast<nas_qos_wred*> (ndi_obj);

    // form attr_list
    std::vector<uint64_t> attr_list;
    attr_list.resize(_set_attributes.len());

    uint_t num_attr = 0;
    for (auto attr_id: _set_attributes) {
        if (attr_id != BASE_QOS_WRED_PROFILE_NPU_ID_LIST) {
            attr_list[num_attr++] = attr_id;
        }
    }

    if ((rc = ndi_qos_create_wred_profile (npu_id,
                                   &attr_list[0],
                                   num_attr,
                                   &nas_qos_wred_p->cfg,
                                   &ndi_wred_id))
            != STD_ERR_OK)
    {
        throw nas::base_exception {rc, __PRETTY_FUNCTION__,
            "NDI QoS WRED Create Failed"};
    }
    // Cache the new WRED ID generated by NDI
    set_ndi_obj_id(npu_id, ndi_wred_id);

    return true;

}


bool nas_qos_wred::push_delete_obj_to_npu (npu_id_t npu_id)
{
    t_std_error rc;

    EV_LOG_TRACE(ev_log_t_QOS, 3, "NAS-QOS", "Deleting obj on NPU %d", npu_id);

    if ((rc = ndi_qos_delete_wred_profile(npu_id, ndi_obj_id(npu_id)))
        != STD_ERR_OK)
    {
        throw nas::base_exception {rc, __PRETTY_FUNCTION__,
            "NDI WRED Delete Failed"};
    }

    return true;
}

bool nas_qos_wred::is_leaf_attr (nas_attr_id_t attr_id)
{
    // Table of function pointers to handle modify of Qos wred
    // attributes.
    static const std::unordered_map <BASE_QOS_WRED_PROFILE_t,
                                     bool,
                                     std::hash<int>>
        _leaf_attr_map =
    {
        // modifiable objects
        {BASE_QOS_WRED_PROFILE_GREEN_ENABLE,        true},
        {BASE_QOS_WRED_PROFILE_GREEN_MIN_THRESHOLD, true},
        {BASE_QOS_WRED_PROFILE_GREEN_MAX_THRESHOLD,        true},
        {BASE_QOS_WRED_PROFILE_GREEN_DROP_PROBABILITY,     true},
        {BASE_QOS_WRED_PROFILE_YELLOW_ENABLE,            true},
        {BASE_QOS_WRED_PROFILE_YELLOW_MIN_THRESHOLD,    true},
        {BASE_QOS_WRED_PROFILE_YELLOW_MAX_THRESHOLD,    true},
        {BASE_QOS_WRED_PROFILE_YELLOW_DROP_PROBABILITY, true},
        {BASE_QOS_WRED_PROFILE_RED_ENABLE,              true},
        {BASE_QOS_WRED_PROFILE_RED_MIN_THRESHOLD,       true},
        {BASE_QOS_WRED_PROFILE_RED_MAX_THRESHOLD,         true},
        {BASE_QOS_WRED_PROFILE_RED_DROP_PROBABILITY,    true},
        {BASE_QOS_WRED_PROFILE_WEIGHT,        true},
        {BASE_QOS_WRED_PROFILE_ECN_ENABLE,    true},
        {BASE_QOS_WRED_PROFILE_NPU_ID_LIST,   true},

        //The NPU ID list attribute is handled by the base object itself.
    };

    return (_leaf_attr_map.at(static_cast<BASE_QOS_WRED_PROFILE_t>(attr_id)));
}

bool nas_qos_wred::push_leaf_attr_to_npu (nas_attr_id_t attr_id,
                                           npu_id_t npu_id)
{
    t_std_error rc = STD_ERR_OK;

    EV_LOG_TRACE(ev_log_t_QOS, 3, "QOS", "Modifying npu: %d, attr_id %d",
                    npu_id, attr_id);

    qos_wred_struct_t cfg= {0};

    switch (attr_id) {
    case BASE_QOS_WRED_PROFILE_GREEN_ENABLE:
        cfg.g_enable = get_g_enable();
        break;

    case BASE_QOS_WRED_PROFILE_GREEN_MIN_THRESHOLD:
        cfg.g_min = get_g_min();
        break;

    case BASE_QOS_WRED_PROFILE_GREEN_MAX_THRESHOLD:
        cfg.g_max = get_g_max();
        break;

    case BASE_QOS_WRED_PROFILE_GREEN_DROP_PROBABILITY:
        cfg.g_drop_prob = get_g_drop_prob();
        break;

    case BASE_QOS_WRED_PROFILE_YELLOW_ENABLE:
        cfg.y_enable = get_y_enable();
        break;

    case BASE_QOS_WRED_PROFILE_YELLOW_MIN_THRESHOLD:
        cfg.y_min = get_y_min();
        break;

    case BASE_QOS_WRED_PROFILE_YELLOW_MAX_THRESHOLD:
        cfg.y_max = get_y_max();
        break;

    case BASE_QOS_WRED_PROFILE_YELLOW_DROP_PROBABILITY:
        cfg.y_drop_prob = get_y_drop_prob();
        break;

    case BASE_QOS_WRED_PROFILE_RED_ENABLE:
        cfg.r_enable = get_r_enable();
        break;

    case BASE_QOS_WRED_PROFILE_RED_MIN_THRESHOLD:
        cfg.r_min = get_r_min();
        break;

    case BASE_QOS_WRED_PROFILE_RED_MAX_THRESHOLD:
        cfg.r_max = get_r_max();
        break;

    case BASE_QOS_WRED_PROFILE_RED_DROP_PROBABILITY:
        cfg.r_drop_prob = get_r_drop_prob();
        break;

    case BASE_QOS_WRED_PROFILE_WEIGHT:
        cfg.weight = get_weight();
        break;

    case BASE_QOS_WRED_PROFILE_ECN_ENABLE:
        cfg.ecn_enable = get_ecn_enable();
        break;

    case BASE_QOS_WRED_PROFILE_NPU_ID_LIST:
        // handled separately, not here
        break;

    default:
            STD_ASSERT (0); //non-modifiable object
    }

    if (attr_id != BASE_QOS_WRED_PROFILE_NPU_ID_LIST) {
        rc = ndi_qos_set_wred_profile_attr(npu_id,
                                   ndi_obj_id(npu_id),
                                   (BASE_QOS_WRED_PROFILE_t)attr_id,
                                   &cfg);
        if (rc != STD_ERR_OK) {
            throw nas::base_exception {rc, __PRETTY_FUNCTION__,
                "NDI attribute Set Failed"};
        }
    }

    return true;
}

